# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Geo-Google
version:      0.01
version_from: lib/Geo/Google.pm
installdirs:  site
requires:
    LWP::Simple:                   0
    URI::Escape:                   0
    XML::DOM:                      0
    XML::DOM::XPath:               0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
